supply_chain:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('SUPPLY_CHAIN_DB_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbt_dev
      threads: 4
